version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongodb:27017/nestdb
      - DB_NAME=my_db
    depends_on:
      - mongodb

  mongodb:
    container_name: my-web-app-container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
  